export const timezoneAbbreviations: Record<string, string> = {
    "Pacific/Honolulu": "(GMT-10:00) Honolulu",
    "America/Los_Angeles": "(GMT-08:00) Los Angeles",
    "America/Vancouver": "(GMT-08:00) Vancouver",
    "America/Denver": "(GMT-07:00) Denver",
    "America/Chicago": "(GMT-06:00) Chicago",
    "America/New_York": "(GMT-05:00) New York",
    "America/Toronto": "(GMT-05:00) Toronto",
    "America/Sao_Paulo": "(GMT-03:00) Sao Paulo",
    "Europe/London": "(GMT+00:00) London",
    "Europe/Dublin": "(GMT+00:00) Dublin",
    "Africa/Lagos": "(GMT+01:00) Lagos",
    "Europe/Oslo": "(GMT+01:00) Oslo",
    "Europe/Stockholm": "(GMT+01:00) Stockholm",
    "Europe/Copenhagen": "(GMT+01:00) Copenhagen",
    "Europe/Berlin": "(GMT+01:00) Berlin",
    "Europe/Amsterdam": "(GMT+01:00) Amsterdam",
    "Europe/Paris": "(GMT+01:00) Paris",
    "Europe/Madrid": "(GMT+01:00) Madrid",
    "Europe/Rome": "(GMT+01:00) Rome",
    "Europe/Brussels": "(GMT+01:00) Brussels",
    "Europe/Luxembourg": "(GMT+01:00) Luxembourg",
    "Europe/Zurich": "(GMT+01:00) Zurich",
    "Africa/Cairo": "(GMT+02:00) Cairo",
    "Africa/Johannesburg": "(GMT+02:00) Johannesburg",
    "Europe/Athens": "(GMT+02:00) Athens",
    "Europe/Helsinki": "(GMT+02:00) Helsinki",
    "Europe/Istanbul": "(GMT+03:00) Istanbul",
    "Europe/Moscow": "(GMT+03:00) Moscow",
    "Asia/Kolkata": "(GMT+05:30) Kolkata",
    "Asia/Shanghai": "(GMT+08:00) Shanghai",
    "Asia/Singapore": "(GMT+08:00) Singapore",
    "Asia/Tokyo": "(GMT+09:00) Tokyo",
    "Australia/Sydney": "(GMT+11:00) Sydney",
    "Australia/Melbourne": "(GMT+11:00) Melbourne",
    "Pacific/Auckland": "(GMT+13:00) Auckland",
  };
  